poetry: Skip packages with directory source in lockfile
Path dependencies are apparently added to poetry.lock as
directory-sourced packages, and this was causing issues.

This fixes the following error:

    Traceback (most recent call last):
      File ".../tools/poetry_translator.py", line 333, in <module>
        main(parse_flags())
      File ".../tools/poetry_translator.py", line 274, in main
        lock_set = translate(
                   ^^^^^^^^^^
      File ".../tools/poetry_translator.py", line 204, in translate
        files = files_by_package_name[package_listed_name]
                ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
    KeyError: 'path-dependency'