Add more module_ctx.watch calls
It seems like without these changing the generated bzl lockfile can
result in not reruning these rules and getting failures like:

```
ERROR: no such package '@@[unknown repo 'pycross_lock_file_wheel_mypy_1.16.1_cp312_cp312_manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64' requested from @@rules_pycross++lock_file+modular_pip_lock_file_repo (did you mean 'pycross_lock_file_wheel_mypy_1.13.0_cp312_cp312_manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64'?)]//file': The repository '@@[unknown repo 'pycross_lock_file_wheel_mypy_1.16.1_cp312_cp312_manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64' requested from @@rules_pycross++lock_file+modular_pip_lock_file_repo (did you mean 'pycross_lock_file_wheel_mypy_1.13.0_cp312_cp312_manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64'?)]' could not be resolved: No repository visible as '@pycross_lock_file_wheel_mypy_1.16.1_cp312_cp312_manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64' from repository '@@rules_pycross++lock_file+modular_pip_lock_file_repo'
```

Right after you introduced the new repo that should satisfy this error